// <auto-generated />
// This file is regenerated each time you run: dotnet ef migrations add <MigrationName>
// Do not edit manually.
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using LedgerSystem.Infrastructure.Persistence;

#nullable disable

namespace LedgerSystem.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(LedgerDbContext))]
    partial class LedgerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            // ── User ─────────────────────────────────────────────────────────────
            modelBuilder.Entity("LedgerSystem.Domain.Entities.User", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uuid")
                    .HasColumnName("id")
                    .HasDefaultValueSql("gen_random_uuid()");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("created_at")
                    .HasDefaultValueSql("NOW()");

                b.Property<string>("Email")
                    .IsRequired()
                    .HasMaxLength(255)
                    .HasColumnType("character varying(255)")
                    .HasColumnName("email");

                b.Property<string>("PasswordHash")
                    .IsRequired()
                    .HasColumnType("text")
                    .HasColumnName("password_hash");

                b.Property<string>("Role")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("character varying(50)")
                    .HasColumnName("role");

                b.Property<DateTime>("UpdatedAt")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("updated_at")
                    .HasDefaultValueSql("NOW()");

                b.HasKey("Id");
                b.HasIndex("Email").IsUnique().HasDatabaseName("idx_users_email");
                b.ToTable("users");
            });

            // ── Wallet ───────────────────────────────────────────────────────────
            modelBuilder.Entity("LedgerSystem.Domain.Entities.Wallet", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uuid")
                    .HasColumnName("id")
                    .HasDefaultValueSql("gen_random_uuid()");

                b.Property<decimal>("Balance")
                    .HasColumnType("numeric(19,4)")
                    .HasColumnName("balance")
                    .HasDefaultValue(0m);

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("created_at")
                    .HasDefaultValueSql("NOW()");

                b.Property<string>("Currency")
                    .IsRequired()
                    .HasMaxLength(3)
                    .HasColumnType("character(3)")
                    .HasColumnName("currency");

                b.Property<bool>("IsActive")
                    .HasColumnType("boolean")
                    .HasColumnName("is_active")
                    .HasDefaultValue(true);

                b.Property<Guid>("UserId")
                    .HasColumnType("uuid")
                    .HasColumnName("user_id");

                b.HasKey("Id");
                b.HasIndex("UserId").HasDatabaseName("idx_wallets_user_id");
                b.HasIndex("UserId", "Currency").HasDatabaseName("idx_wallets_user_currency");
                b.ToTable("wallets", t =>
                {
                    t.HasCheckConstraint("ck_wallets_balance_non_negative", "balance >= 0");
                });
            });

            // ── Transfer ─────────────────────────────────────────────────────────
            modelBuilder.Entity("LedgerSystem.Domain.Entities.Transfer", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uuid")
                    .HasColumnName("id")
                    .HasDefaultValueSql("gen_random_uuid()");

                b.Property<decimal>("Amount")
                    .HasColumnType("numeric(19,4)")
                    .HasColumnName("amount");

                b.Property<DateTime?>("CompletedAt")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("completed_at");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("created_at")
                    .HasDefaultValueSql("NOW()");

                b.Property<string>("Currency")
                    .IsRequired()
                    .HasMaxLength(3)
                    .HasColumnType("character(3)")
                    .HasColumnName("currency");

                b.Property<string>("Description")
                    .HasColumnType("text")
                    .HasColumnName("description");

                b.Property<Guid>("DestinationWalletId")
                    .HasColumnType("uuid")
                    .HasColumnName("destination_wallet_id");

                b.Property<string>("IdempotencyKey")
                    .IsRequired()
                    .HasMaxLength(255)
                    .HasColumnType("character varying(255)")
                    .HasColumnName("idempotency_key");

                b.Property<Guid>("SourceWalletId")
                    .HasColumnType("uuid")
                    .HasColumnName("source_wallet_id");

                b.Property<string>("Status")
                    .IsRequired()
                    .HasMaxLength(20)
                    .HasColumnType("character varying(20)")
                    .HasColumnName("status");

                b.HasKey("Id");
                b.HasIndex("IdempotencyKey").IsUnique().HasDatabaseName("idx_transfers_idempotency_key");
                b.HasIndex("SourceWalletId").HasDatabaseName("idx_transfers_source_wallet_id");
                b.HasIndex("DestinationWalletId").HasDatabaseName("idx_transfers_destination_wallet_id");
                b.HasIndex("CreatedAt").HasDatabaseName("idx_transfers_created_at");
                b.ToTable("transfers", t =>
                {
                    t.HasCheckConstraint("ck_transfers_amount_positive", "amount > 0");
                    t.HasCheckConstraint("ck_transfers_different_wallets",
                        "source_wallet_id != destination_wallet_id");
                });
            });

            // ── LedgerEntry ──────────────────────────────────────────────────────
            modelBuilder.Entity("LedgerSystem.Domain.Entities.LedgerEntry", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uuid")
                    .HasColumnName("id")
                    .HasDefaultValueSql("gen_random_uuid()");

                b.Property<decimal>("Amount")
                    .HasColumnType("numeric(19,4)")
                    .HasColumnName("amount");

                b.Property<decimal>("BalanceAfter")
                    .HasColumnType("numeric(19,4)")
                    .HasColumnName("balance_after");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("created_at")
                    .HasDefaultValueSql("NOW()");

                b.Property<string>("Description")
                    .HasColumnType("text")
                    .HasColumnName("description");

                b.Property<string>("EntryType")
                    .IsRequired()
                    .HasMaxLength(10)
                    .HasColumnType("character varying(10)")
                    .HasColumnName("entry_type");

                b.Property<Guid?>("TransferId")
                    .HasColumnType("uuid")
                    .HasColumnName("transfer_id");

                b.Property<Guid>("WalletId")
                    .HasColumnType("uuid")
                    .HasColumnName("wallet_id");

                b.HasKey("Id");
                b.HasIndex("WalletId", "CreatedAt").HasDatabaseName("idx_ledger_entries_wallet_created_at");
                b.HasIndex("CreatedAt").HasDatabaseName("idx_ledger_entries_created_at");
                b.ToTable("ledger_entries", t =>
                {
                    t.HasCheckConstraint("ck_ledger_entries_amount_positive", "amount > 0");
                });
            });

            // ── IdempotencyKey ───────────────────────────────────────────────────
            modelBuilder.Entity("LedgerSystem.Domain.Entities.IdempotencyKey", b =>
            {
                b.Property<string>("Key")
                    .HasMaxLength(255)
                    .HasColumnType("character varying(255)")
                    .HasColumnName("key");

                b.Property<Guid>("UserId")
                    .HasColumnType("uuid")
                    .HasColumnName("user_id");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("created_at")
                    .HasDefaultValueSql("NOW()");

                b.Property<DateTime>("ExpiresAt")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("expires_at")
                    .HasDefaultValueSql("NOW() + INTERVAL '24 hours'");

                b.Property<string>("RequestPath")
                    .IsRequired()
                    .HasColumnType("text")
                    .HasColumnName("request_path");

                b.Property<string>("ResponseBody")
                    .IsRequired()
                    .HasColumnType("jsonb")
                    .HasColumnName("response_body");

                b.Property<int>("ResponseStatus")
                    .HasColumnType("integer")
                    .HasColumnName("response_status");

                b.HasKey("Key", "UserId");
                b.HasIndex("ExpiresAt").HasDatabaseName("idx_idempotency_keys_expires_at");
                b.ToTable("idempotency_keys");
            });

            // ── Relationships ────────────────────────────────────────────────────
            modelBuilder.Entity("LedgerSystem.Domain.Entities.Wallet", b =>
            {
                b.HasOne("LedgerSystem.Domain.Entities.User", null)
                    .WithMany("Wallets")
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();
            });

            modelBuilder.Entity("LedgerSystem.Domain.Entities.Transfer", b =>
            {
                b.HasOne("LedgerSystem.Domain.Entities.Wallet", null)
                    .WithMany()
                    .HasForeignKey("SourceWalletId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.HasOne("LedgerSystem.Domain.Entities.Wallet", null)
                    .WithMany()
                    .HasForeignKey("DestinationWalletId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();
            });

            modelBuilder.Entity("LedgerSystem.Domain.Entities.LedgerEntry", b =>
            {
                b.HasOne("LedgerSystem.Domain.Entities.Wallet", null)
                    .WithMany("LedgerEntries")
                    .HasForeignKey("WalletId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.HasOne("LedgerSystem.Domain.Entities.Transfer", null)
                    .WithMany()
                    .HasForeignKey("TransferId")
                    .OnDelete(DeleteBehavior.Restrict);
            });

            modelBuilder.Entity("LedgerSystem.Domain.Entities.IdempotencyKey", b =>
            {
                b.HasOne("LedgerSystem.Domain.Entities.User", null)
                    .WithMany()
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

            modelBuilder.Entity("LedgerSystem.Domain.Entities.User", b =>
            {
                b.Navigation("Wallets").HasField("_wallets");
            });

            modelBuilder.Entity("LedgerSystem.Domain.Entities.Wallet", b =>
            {
                b.Navigation("LedgerEntries").HasField("_ledgerEntries");
            });
#pragma warning restore 612, 618
        }
    }
}
